name: A

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate
        run: node a.js

      - name: Deal with Git
        run: |
          git stash
          git pull
          git stash pop

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: generate"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
