on:
  push:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: uncenter/setup-taplo@v1.0.5
        with:
          version: "0.8.1"

      - run: taplo fmt foo.toml --check
        shell: bash
