on:
  push:

jobs:
  x:
    runs-on: windows-latest
    steps:
      - shell: bash
        run: |
          ls "C:\\Program Files\\"
          mkdir -p "C:\\Program Files\\taplo\\bin\\"
          touch "C:\\Program Files\\taplo\\bin\\a.txt"
          cat a.txt

